name: OnePlayerSleep
version: 1.16-001
main: stream.azakt.oneplayersleep.OnePlayerSleep
api-version: 1.13
authors: [Azakt]
description: Allows one player to sleep to pass the night.
website: azakt.stream
